### ISSUE TITLE
list(rule, delim) returns singleton instance of `rule` instead of length-1 list of rule

### ISSUE THREAD

**Issue by swadey** [abeschneider/PEGParser#4] opened 2015-01-07 22:12 UTC
I have a grammar like this:
```julia
sexpr  = "(" + list(expr, white_space) + ")"
```

parsing `(1)` returns `1`
parsing `(1 2)` return `[1, 2]`

shouldn't parsing `(1)` return `[1]`?

**Comment by abeschneider** [comment] 2015-01-07 22:22
@swadey I'll take a look into it. If memory serves, there's logic that automatically returns a single value if the array size is of 1 (as a simplification). I think it's probably a bad idea to do that, as it is confusing to users, and creates a non-uniform interface, so I'll take a look into getting rid of that behavior.

**Comment by swadey** [comment] 2015-01-07 22:38
@abeschneider thanks!  There's a related problem you might consider.  Rules like:

```julia
sexpr = "(" + list(expr, white_space) + ")"
```
won't match `()` so that means rule writers have to write a separate rule like this:

```julia
sexpr0 = "(" ?(white_space) + ")"
```

to cover empty lists. I believe many PEG parser libraries have repsep and rep1sep to allow for minimum one and minimum zero lists.

**Comment by abeschneider** [comment] 2015-01-08 03:02
Okay, after some investigation, the reason for this particular behavior is found in the `transform(fn::Function, node::Node, ignore::Set{Symbol})` function, with the lines:

```
if (length(cvalues) == 1)
  cvalues = cvalues[1]
end
```

The reason for this code is actually not due to a simplification, but rather due to nested rules. Specifically, suppose you have something like:
```
a -> b | c
b -> number
c -> string
```

If `b` returns `[5]`, then `a` returns `[[5]]`. There are ways of dealing with this in the custom transforms, but if you have some type of recursive invocation, it can get particularly difficult (see `examples/ml.jl`).

That said, I'm not convinced the current code is the most sensible. I'm going to spend a little more time going through the code to see if there isn't a better solution.

**Comment by abeschneider** [comment] 2015-01-08 03:04
As for the `list` issue, if you open up a second issue, I can tackle that. One option might be to have `list` take an optional parameter for the min/max matches allowed.

**Comment by swadey** [comment] 2015-01-08 03:08
sure thing.
wade

**Comment by swadey** [comment] 2015-01-08 13:34
i opened a separate issue for you.

**Comment by abeschneider** [comment] 2015-01-09 12:46
Okay, I'm changing the behavior to always return a list. However, before I commit the code, I need to fix one more thing. The issue is that now a large number of rules has to be defined which looks like:

```
tovalue(node, toks, ::MatchRule{:RuleName}) = toks[1]
```

If you don't do this, then the result will be large number of nested lists. I'm investigating ways of simplifying this (I think libraries like pyparsing deal with this by allowing actions in the rules).

**Comment by swadey** [comment] 2015-01-09 13:28
I guess there's a bigger design question about the semantic actions / grammar_transform.  In your example `toks` is always an array and there's some implicit autoflattening that's happening?

So with a grammar like this:
```julia
int = r"\d+"
x = "[" + int + "]"
y = "(" + list(int, white_space) + ")"
```
and an expression like this: `[10]`, the `toks` array when calling the grammar_transform for `x` looks like: `{ "[", "10", "]" }` 

Whereas for an expression like this: `(10 20)`, the `toks` array looks like `{ "(", "10", "20", ")" }`

Perhaps another solution would be to make list parser return an list of list.  That way the result `list()` is distinguished from result sequence parsing.  That would mean that `(10 20)` in this case would be parsed into a toks array that looks like `{ "(", ["10", "20"], ")" } and list() would return `[["10", "20"]]`.

You're right that other libraries handle this differently.  I'm used to scala's parser combinator implementation which specifies actions paired with rules directly and the return types of actions are variable.

**Comment by abeschneider** [comment] 2015-01-09 15:41
Going away from the direct tying of actions to rules is definitely an experimental part of this library, and may ultimately backfire. I actually have code to define an action per rule (in my GrammaticalEvolution library, where you can do: `rule[action] = ...`), and it will eventually be added, but I'm trying to see if we can keep the two separated for now. The rationale is that it would be nice to be able to re-use grammars across multiple tasks by requiring only the transformations be rewritten.

The auto-flattening was put in there to get things working at the time (the code of the library was written in a weekend), but I think I can get it to work without that requirement. I think by adding in notation to the rules that allow either suppression of tokens (e.g., pyparsing's `rule.suppress()`) or automatic unpacking, things can be simplified again. I'm imagining something along the lines of:

```
number = integer[1] | float[1]
```

to indicate that the result of the rule should be indexed.

**Comment by abeschneider** [comment] 2015-01-10 04:15
It's still a work in progress, but I've added two new features:
- A suppression operator `-(rule)`, which means that the rule doesn't get added to the tree
- A selection operator `rule[s]`, where `s` determines which children get added to the tree

I made a quick example:
```
@grammar calcgrammar begin
  start = expr
  number = (space + r"[1-9][0-9]*")[2]
  expr = -lparen + op + (number | expr)[1] + (number | expr)[1] + -rparen
  op = (add | sub | mult | div)[1]

  add = (-space + "+")[1]
  sub = (-space + "-")[1]
  mult = (-space + "*")[1]
  div = (-space + "/")[1]
  lparen = space + "("
  rparen = space + ")"
  space = r"[ \n\r\t]*"
end
```

Using the grammar:

```
data = "(+ 1 2)"
(ast, pos, error) = parse(calcgrammar, "(+ 1 2)")
println(ast)
```

gives:

```
node(start) {ReferencedRule}
1: node(expr) {AndRule}
  1: node(add.2) {'+',Terminal}
  2: node(number.2) {'1',RegexRule}
  3: node(number.2) {'2',RegexRule}
```

The tree produced is now much simpler and lends itself to performing transforms better than a full tree.

Currently the selection is just an integer, but I think it makes sense to also allow it to be a function (and possibly slices). I think the syntax is simple enough that it doesn't get in the way of the grammar, and hopefully doesn't make things too much more complicated.

**Comment by swadey** [comment] 2015-01-12 03:30
That looks very cool and, yes, having an arbitrary function instead of indexing would be great.

**Comment by abeschneider** [comment] 2015-01-12 15:23
I'm hoping to commit something soon .. the code is implemented, but I'm playing around to make sure I get the semantics correct.

**Comment by swadey** [comment] 2015-01-12 15:35
very cool.  One question: how did you intend to extend the `[i]` notation to allow for arbitrary functions?

**Comment by abeschneider** [comment] 2015-01-13 13:25
I've committed a version of the new code. The tests run, but some of the examples need to still be fixed. The code in `examples/calc.jl` is fully working, and shows the new code being used.

A quick example:
```
number = (-space + r"[1-9][0-9]*")[1]
```

Does two things. First, it suppresses `space`, and second, it skips the **and** rule, so number will only take on a numeric value. You could in theory do:

```
number = (space + r"[1-9][0-9]*")[2]
```

except that if there is no space, the rule will only have a single value, and you will get a bounds-error.


The rule-selection works by replacing the current node in the tree by the child while keeping the name of the parent class. I think this behavior supports most use-cases. However, allowing a function instead of a function could allow any user-defined behavior to be used instead. To give an example, the current selection code looks like:

```
    child = ast.children[rule.selection]
    node = Node(ast.name, child.value, child.first, child.last, child.children, child.ruleType)
    return (node, pos, error)
```

if `rule.selection` is a function, the code may be something like:

```
   node = rule.selection(ast)
   return (node, pos, error)
```

So the function passed in takes the current AST and returns the transformed (as `node`). Then, to invoke it, you might do something like:

```
value = (number | expr)[(ast) -> node.children[1]]
```

**Comment by swadey** [comment] 2015-01-14 13:19
Ok, that sounds really great.  I'll give it a try and report back to you. Is this pushed and updated in metadata?

**Comment by abeschneider** [comment] 2015-01-14 13:39
Not yet, I wanted to fix all the example code first. I am planning in a couple hours to also commit the code to allow the arbitrary functions.

**Comment by abeschneider** [comment] 2015-01-14 14:39
Sorry, updates will have to wait. The firewall I'm behind is making pushing the updates difficult.

**Comment by abeschneider** [comment] 2015-01-15 04:07
Okay, updates committed. The examples showing the new features are:

`csv.jl` - CSV parser
`ml.jl` - a LISP-like grammar that translates into results into Julia expressions
`calc.jl` - a reverse-notation calculator (which also translates into Julia expressions)

I still worry whether the results of `rule[i]` is obvious. I could allow only functions to be specified instead, but that produces fairly verbose code. One option to reduce verbosity may be to create simplified notation for the functions (e.g. something like Swift).

**Comment by abeschneider** [comment] 2015-01-24 15:01
Okay, unless there are any other issues, I'm closing this. I'm currently investigating the ability to also add actions to rules (which is a bit antithetical to the current approach). The idea is to allow the user to be able to choose whether the tree should be automatically created or create his/her own.

**Closed by abeschneider** 2015-01-24 15:01 UTC

**Comment by swadey** [comment] 2015-01-28 20:07
Apologies for the delay but I finally had an opportunity to try this last night.  I ran into problems with the `[1]` notation.  Specifically, the issue is that transformations are hard to specify when intermediate nodes are elided.  Here's an example of what I mean:

```julia
@grammar test begin
  float_no_dot_matcher   = r"[-+]?[0-9]*[0-9]+([eE][-+]?[0-9]+)?[Ff]"
  float_with_dot_matcher = r"[-+]?[0-9]*\.[0-9]+([eE][-+]?[0-9]+)?[Ff]"
  int                    = r"\d+"
  float = (float_no_dot_matcher | float_with_dot_matcher)[1]
  start = (float | int)[1]
end

toexpr(node, cnodes, ::MatchRule{:float}) = float32(node.value[1:end-1])
toexpr(node, cnodes, ::MatchRule{:int})   = int32(node.value[1:end-1])
toexpr(node, cnodes, ::MatchRule{:default}) = cnodes
```

Neither of the `:float` or `:int` transform rules will be able to apply.  `start` and `RegexRule` are the only nodes left in the tree making it unclear how to apply transformation.  Is there a way to unify tree transformations (ala `[]` or getindex) with `transform()`?  Perhaps an explicit AST object isn't needed during parsing?  Could the user specify a constructor with each rule that creates an object upon rule firing instead of creating a parser-specific `Node` object?

**Comment by abeschneider** [comment] 2015-01-29 13:09
The issue is that that the `[i]` notation takes the parent's node type, but the child's value. Thus, `start = (float | int)[1]` gives you (printing out the AST):
```
node(start) {'1',RegexRule}
```

However, if you do `start = (float | int)[(ast) -> ast.children[1]]`, you get:
```
node(int) {'1',RegexRule}
```

So the `[i]` notation is doing the correct thing, but the syntax is potentially confusing. The rationale for its current formulation is to support **and** expressions. In theory I could make it so it does different things for **and* and **or** expressions, but that is potentially confusing. I could also make special syntax for `(ast) - >ast.children[1]`, but I haven't found anything satisfactory. A third option is to get rid of the special syntax altogether, and just export functions with more useful names. I like the third option the best right now, but haven't come up with good names.

I opened another issue for allowing the parser to not create an AST, and attach semantic actions. I've already made some progress in refactoring the code to support this (the biggest obstacle is the current caching mechanism). However, I think it's still useful for have tree operations in the rules.

I'll have to think about moving the tree transforms to `transform`. The issue is this was done in part to avoid having to write an exhaustive `transform` list, which I think you would have to if you took the AST transform rules out of the grammar.

**Comment by swadey** [comment] 2015-01-29 14:36
Thanks.  I now understand the distinction between `[i]` and `ast -> ast.children[i]`.  That will certainly solve my immediate problem.

For my applications, what I really want is to generate my own AST.  The two methods of transformation, namely tree transformation and `transform`, are both mechanisms for doing this.  That said, it feels like it would be simpler to express the appropriate transformations needed with semantic actions associated with rules that would allow the user to construct a custom tree.  The reason this is simpler is that it allows combinations of node deletions, insertions, transformations and evaluation of nodes to occur in one place.  I believe this is the way that bison/yacc and scala's parser combinators both work:

Bison:
```expr: expr '+' expr   { $$ = $1 + $3; } ;```

Scala:
```scala
  val FloatWithDotMatcher  = """[-+]?[0-9]*\.[0-9]+([eE][-+]?[0-9]+)?[Ff]?""".r
  val FloatNoDotMatcher    = """[-+]?[0-9]*[0-9]+([eE][-+]?[0-9]+)?[Ff]""".r
  def float    = (FloatWithDotMatcher | FloatNoDotMatcher ) ^^ { x => x.toFloat }
  def int      = """[-+]?\d+""".r ^^ { x => x.toInt }
  def expr   = (float | int)
```

In terms of implementation, the scala parser combinator library doesn't introduce doesn't introduce nodes for `|` or regex expressions which, I think, eliminates a lot of confusion (i.e. these rules have default actions that return their children).  For `+` (which scala writes as `~`), it defaults to returning a structure that looks like `~(x, y, ...)` which you can then transform like this: `^^ { case ~(x, y) => x & y }`

**Comment by abeschneider** [comment] 2015-01-29 15:46
I think these are all good points. The current structure really is a result
of the original caching mechanism, which once I refactor, should allow the
support of user-defined semantic actions.

I like the idea of | defaulting to `(ast) -> ast.children[1]`, so that
might be a good start.

I also have to figure out the best syntax for creating the actions.
Unfortunately, since Julia doesn't use curly-braces for blocks, it makes
inserting actions the way Scala or Bison do a bit cumbersome.
Re-appropriating the selection rule might be the best option (it's
essentially what it is anyways), so it might look like:

```
int =  r"[-+]?\d+"[(node) -> parseint(node.value)]
```

I can also allow rules to be defined on the LHS:
```
int[(node)- > parseint(node.value)] = r"[-+]?\d+"
```

which is a little more readable if you have a single action.

**Comment by swadey** [comment] 2015-01-29 18:14
Regarding the braces:  I understand that you're limited to Julia syntax.  That said, it's still possible to do more complex things in named functions.  That would mean allowing `getindex(f::Symbol)` to be translated a `f()`

**Comment by abeschneider** [comment] 2015-01-29 21:29
Can you expand on that? I'm not sure I understand. Is that different from
the current use of `[fn]`?

**Comment by swadey** [comment] 2015-01-29 23:41
Sorry, I didn't know that you could already refer to a function by name in getindex. I was suggesting that complex functions could be declared outside the grammar as a named function or variable.  I was mentioning this as a potential solution for the curly brace/block syntax issue you had brought up in your last comment.

**Comment by abeschneider** [comment] 2015-01-31 15:40
No problem, just wanted to make sure I understood your point. I should add, it *should* allow that, but currently there's an `eval` in the macro which disallows named functions (anonymous functions still work fine). Once I fix that, it should be fully working.

**Comment by abeschneider** [comment] 2015-02-14 14:38
@swadey Okay, it took some time, but I've figured out how to change the macro properly so that the function's name gets evaluated in the proper namespace (I had a solution for the GrammaticalEvolution library, but unfortunately things are slightly different here, which is what was causing the issue).

You can now do similar semantics to Scala's and somewhat similar to Bisons (I'd love to be able to also support a short-hand version that looks something like `$$ = $1`).

Before I commit the changes I'm going to:

1. Write a few more test cases to make sure things are working correctly.
2. Try to get rid of the hard dependence on the Node type .. I would like to be able to allow user-defined trees to be allowed as well allow non-ASTs scenarios (e.g. an immediate evaluation calculator).

**Comment by swadey** [comment] 2015-02-14 17:23
Very cool!

**Comment by abeschneider** [comment] 2015-02-26 13:33
@swadey I've added a comment to the currently open issue for semantic actions (it's better to continue the conversation there). I now have 3 examples with it working.

**Comment by swadey** [comment] 2015-02-28 19:40
Cool. Look forward to trying it. 

thanks,
wade
